### ISSUE TITLE
Bug: Words separated with a hypen and surrounding spaces are joined and showed as invalid

### ISSUE THREAD

**Issue by Ambro17** [JulienPalard/pospell#15]
Steps to reproduce.
1. Create a valid .po file with the following content
```
first - word
```
2. Run `pospell  my_previous_file.po`
3. Check that it shows `firstword` as an invalid word as it trims the hyphen with the surrounding spaces.

The problem seems to be this regex `https://github.com/JulienPalard/pospell/blob/master/pospell.py#L136` that is too abarcative. Perhaps we should allow a flag that has a more relaxed replacement policy?

**Comment by JulienPalard** [comment]
Hi! Thanks for reporting!

I fixed the bug by adding a space in place of the removed stuff, this should avoid words to be glued together, can you please try version 1.0.4?

**Comment by Ambro17** [comment]
Wow that's fast, thank you! I will check today and confirm if it was solved

**Comment by JulienPalard** [comment]
I also took time to work on https://github.com/JulienPalard/pospell/issues/12, TL;DR: pospell was not reporting words that was "too wrong" (for which hunspell has no near match).

I will merge it, but not today, it's in this PR: https://github.com/JulienPalard/pospell/pull/16 if you want to test it against your repo, in case it spots errors that were not previously spotted.

**Comment by Ambro17** [comment]
I can confirm the bug was fixed. I've not yet tried the other branch you suggested though
