### ISSUE TITLE
Compound words not correctly handled by pospell

### ISSUE THREAD

**Issue by mondeja** [JulienPalard/pospell#19]
Consider this simple `*.po` file:

```po
#
msgid ""
msgstr ""

msgid "pub/sub"
msgstr "pub/sub"
```

Let's try to generate an error for `pub/sub` with `hunspell` using `es_ES` dictionary: 

```bash
$ echo 'pub/sub' | hunspell -d es_ES -l
pub
sub
```
If you run it, you can see that the words `pub` and `sub` are marked as incorrect, and **separated each one** by newline characters.

If I try the same with `pospell`, I have the next result:
```bash
$ pospell --language es_ES prueba.po
```

... nothing is marked as incorrect.

### Problem

Printing the output of the call `subprocess.run` to hunspell, I can see: `CompletedProcess(args=['hunspell', '-d', 'es_ES', '-l'], returncode=0, stdout='pub\nsub\n')`. So the stdout is `pub\nsub\n`.

After the call to hunspell, in the source code appears this:

```python
line_of_words = defaultdict(set)
for line, text in enumerate(text_for_hunspell.split("\n"), start=1):
    for word in text.split():
        line_of_words[word].add(line)
for misspelled_word in set(output.stdout.split("\n")):
    for line_number in line_of_words[misspelled_word]:
        errors.append((po_file, line_number, misspelled_word))
```

So, the code that finds the line numbers for the words supposes that hunspell doesn't splits the words if it found characters as `/`, `-`... With some prints in the source code is easy to understand:

```python
print(line_of_words)
for misspelled_word in set(output.stdout.split("\n")):
    if misspelled_word not in line_of_words:
        print("---> mispelled word '%s' doesn't exists in line_of_words" % misspelled_word)
    for line_number in line_of_words[misspelled_word]:
        errors.append((po_file, line_number, misspelled_word))
```

The complete output is:

```
CompletedProcess(args=['hunspell', '-d', 'es_ES', '-l'], returncode=0, stdout='pub\nsub\n')
defaultdict(<class 'set'>, {'pub/sub': {6}})
---> mispelled word '' doesn't exists in line_of_words
---> mispelled word 'pub' doesn't exists in line_of_words
---> mispelled word 'sub' doesn't exists in line_of_words
```

so `pub` and `sub` are not added to `errors` list because their line numbers are not found.

## Possible workaround
Compond words behaviour are related to [compounding options of hunspell](https://manned.org/hunspell/ebce193d#head5) and depends on the dictionaries in use. Something like this may increase correct positives, but is a poor workaround:

```python
import re

for line, text in enumerate(text_for_hunspell.split("\n"), start=1):
    for word in re.split(r' |/|-', text):
        line_of_words[word].add(line)
```

The ideal solution would be to parse the `.aff` file for the languages passed and create a set of compounding rules to split correctly the words.

**Comment by JulienPalard** [comment]
Hi! Thanks for reporting.

I tried something a bit dumb, but it works without false positives on python-docs-fr, so let it give a try.

I tried to release an alpha version but bumpversion messed it... so here we go with my test release as pospell 1.0.6 on pypi :p tell me how it goes.

**Comment by mondeja** [comment]
Now it works as expected, thank you! :+1:

**Comment by mondeja** [comment]
Is expected to exist pospell version 1.0.6 as git tag, or the next tag will be 1.0.7?

**Comment by JulienPalard** [comment]
I probably forgot to git push --tags, I'll check this.

**Comment by JulienPalard** [comment]
done.
