### ISSUE TITLE
Drop string interpolation placeholders

### ISSUE THREAD

**Issue by xi** [JulienPalard/pospell#8]
placeholders like `%s`, `%(foo)s`, or `{foo}` should be ignored.

**Comment by JulienPalard** [comment]
Do you have examples with them? A link to a repo would be appreciated too.

**Comment by xi** [comment]
Our repo is at https://git.mpib-berlin.mpg.de/castellum/castellum/

The example is

```
#, python-format
msgid ""
"Only %(added)s out of %(batch_size)s potential participants could be found for "
"this study. These have been added."
```

I saw that pospell ignores *some* kind of interpolation, so I changed it to this:

```
#, python-brace-format
msgid ""
"Only {added} out of {batch_size} potential participants could be found for "
"this study. These have been added."
```

Still didn't work. It only work when I removed the underscore:

```
#, python-brace-format
msgid ""
"Only {added} out of {batchsize} potential participants could be found for "
"this study. These have been added."
```

**Comment by JulienPalard** [comment]
OK so the issue is broader I think, currently pospell is only focused at searching spellings in po files that **are storing restructuredText**. Looks like you're using pospell for a po file **not** containing rst.

I'm surprised you don't have errors during the rst parsing... The "it removes some kind of interpolation" probably due to rst parsing only.

What do you think about adding a `--rst` flag to pospell to enable/disable rst parsing and another "--interpolation" to enable/disable drop of interpolated strings?

As typicaly we don't have interpolated strings in rst and vice-versa.

**Comment by xi** [comment]
> What do you think about adding a `--rst` flag to pospell to enable/disable rst parsing

That would be awesome. But it is really up to you whether you want to change the direction of this project in this way. I would also be happy if you could point me to some other tool that does what I need.

>  and another `--interpolation` to enable/disable drop of interpolated strings?

I am not completely sure if this is required.

"Sphinx variables" are already dropped. I am not exactly sure what that is because I could not find anything about it in the sphinx docs. However, adding underscore as acceptable character would already help a lot.

Also note that our po file contains a comment like `python-format` or `python-brace-format` on each entry that uses this kind of interpolation. It would be nice if we could automatically detect which entry uses which kind of formatting and decide what to do based on that.


Either way, I would be happy to help with the necessary changes. I will try to get around to it during next week.

**Comment by JulienPalard** [comment]
As the name of the project does not indicate it's rst only, and as the project looks usefull outside "rst in po" context, it feel right to generalize it a bit.

The `Sphinx variable` rule could be enhanced to match your dashed variables, but not the `%(added)s` format. Let's simply add a rule to ignore `%(added)s` format and not add `--interpolation` for the moment.

**Comment by xi** [comment]
I checked again that `%(foo)s` is already covered, even with underscores. What is still missing though is something like `%s` or `%(foo)i`

**Comment by JulienPalard** [comment]
If it's as simple as that, you can add two simple regex to cover them, I'll gladly merge them.

**Comment by xi** [comment]
I think the `%s` (without a name) is not as relevant because position dependent formatting is discouraged for translations anyway. So I consider this fixed. Thanks for the quick feedback!
